### ISSUE TITLE
self._quota_project_id Error on credentials

### ISSUE THREAD

**Issue by Jarn40** [googleapis/google-auth-library-python-oauthlib#67]
I'm having problem to use this lib on ubuntu server, some how the lib doenst work. my code runs in windows10, ubuntu desktop 18.04, but when I try to run it on ubuntu server headless 18.04 it crashes.
```

Traceback (most recent call last):
  File "mongoToDriveUpdater.py", line 147, in <module>
    print(API.get("10kK02ho-qWemN8FTMu6r2zaF7c0Eoi-8"))
  File "mongoToDriveUpdater.py", line 81, in get
    file_resource = self.service.files().get(fileId=file_id, fields='webContentLink').execute()
  File "/home/saffira/env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/saffira/env/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/saffira/env/lib/python3.6/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/saffira/env/lib/python3.6/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/home/saffira/env/lib/python3.6/site-packages/google/auth/credentials.py", line 125, in before_request
    self.apply(headers)
  File "/home/saffira/env/lib/python3.6/site-packages/google/oauth2/credentials.py", line 185, in apply
    if self.quota_project_id is not None:
  File "/home/saffira/env/lib/python3.6/site-packages/google/oauth2/credentials.py", line 134, in quota_project_id
    return self._quota_project_id
AttributeError: 'Credentials' object has no attribute '_quota_project_id'

```

at this example I made a class that have a method get for testing, it gets the file specified by ID.

```
def get(self, file_id):
        file_resource = self.service.files().get(fileId=file_id, fields='webContentLink').execute()
        return file_resource
```
as you can see its a normal service.files().get() function call, but I dont know why the request crashes only using ubuntu server headless 18.04.

Im using 
Python 3.6.9
here my  venv "pip3 list", output:
```

cachetools (3.1.1)
certifi (2019.11.28)
chardet (3.0.4)
google-api-python-client (1.7.11)
google-auth (1.8.1)
google-auth-httplib2 (0.0.3)
google-auth-oauthlib (0.4.1)
httplib2 (0.14.0)
idna (2.8)
oauthlib (3.1.0)
pip (9.0.1)
pkg-resources (0.0.0)
pyasn1 (0.4.8)
pyasn1-modules (0.2.7)
pymongo (3.10.0)
requests (2.22.0)
requests-oauthlib (1.3.0)
rsa (4.0)
setuptools (42.0.2)
six (1.13.0)
uritemplate (3.0.0)
urllib3 (1.25.7)
wheel (0.33.6)
```
 
Can someone help me solve this issue?

**Comment by busunkim96** [comment]
Hi,

This a bug introduced in https://github.com/googleapis/google-auth-library-python/issues/405.

There are two ways you can resolve this:
(1) Delete your pickled credentials file (most likely called `token.pickle` if you followed one of our quickstarts). Re-run the script.
(2) Pin to a previous version `google-auth==1.7.2`

**Comment by busunkim96** [comment]
If you have additional issues please follow up in  googleapis/google-auth-library-python#405.

**Comment by Jarn40** [comment]
Thank you, I just did it and worked :)
