### ISSUE TITLE
run_local_server should fail fast if the requested port is already used

### ISSUE THREAD

**Issue by tswast** [googleapis/google-auth-library-python-oauthlib#75]
The following script fails poorly by hanging indefinitely. I believe this is because the token actually gets sent to SimpleHTTPRequestHandler, not the oauth flow server.

```python
import http.server
import socketserver
import threading
import time

from google_auth_oauthlib import flow


CLIENT_ID = ...
CLIENT_SECRET = ...
GOOGLE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"


def occupy_port():
    # Create an HTTP server to take up port 8080.
    Handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", 8080), Handler) as httpd:
        httpd.serve_forever()

server = threading.Thread(target=occupy_port)
server.start()
time.sleep(2)

client_config = {
    "installed": {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob"],
        "auth_uri": GOOGLE_AUTH_URI,
        "token_uri": GOOGLE_TOKEN_URI,
    }
}
app_flow = flow.InstalledAppFlow.from_client_config(
    client_config, scopes=["https://www.googleapis.com/auth/cloud-platform"]
)
credentials = app_flow.run_local_server(port=8080)
assert credentials is not None

server.join(timeout=1)
```

Instead, I would expect `run_local_server` to fail fast (don't open the browser window) due to occupied port. For example, socketserver raises `OSError: [Errno 48] Address already in use`. I'd expect something similar (or a more specific exception) from google-auth-oauthlib.

**Comment by danoscarmike** [comment]
@busunkim96 @bshaffer FYI

**Comment by busunkim96** [comment]
@tswast  I tried running the script you provided but get an `OSError`. Is there something else I need to reproduce the hanging?

```
(env) busunkim@busunkim:~/github/google-auth-library-python-oauthlib$ python3 occupy_port.py 
Traceback (most recent call last):
  File "occupy_port.py", line 22, in <module>
    credentialss = flow.run_local_server(port=8080)
  File "/usr/local/google/home/busunkim/github/google-auth-library-python-oauthlib/google_auth_oauthlib/flow.py", line 452, in run_local_server
    local_server = wsgiref.simple_server.make_server(
  File "/usr/local/google/home/busunkim/.pyenv/versions/3.8.3/lib/python3.8/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/local/google/home/busunkim/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/google/home/busunkim/.pyenv/versions/3.8.3/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/local/google/home/busunkim/.pyenv/versions/3.8.3/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/google/home/busunkim/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

I get the same error if I start a server and try to do `run_local_server` on the same port.

```
(env) busunkim@busunkim:~/github/google-auth-library-python-oauthlib$ python -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
```
```py
from google_auth_oauthlib import flow

flow = flow.InstalledAppFlow.from_client_secrets_file(
                'credentials.json', ['https://www.googleapis.com/auth/drive'])
credentials = flow.run_local_server(port=8080)
```

**Comment by tswast** [comment]
I can reliably get it to hang on macOS with the following packages on a Python 3.7 environment

```
$ conda list | grep auth
google-auth               1.19.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                      py_2    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
pydata-google-auth        1.1.0              pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.2.0              pyh9f0ad1d_1    conda-forge
```

**Comment by busunkim96** [comment]
Thanks Tim!

I think I've tracked down the root cause. [`WSGIServer`](https://github.com/python/cpython/blob/7c4065d305228aa406675224d631f81964d12855/Lib/wsgiref/simple_server.py#L42) inherits from `HTTPServer` which sets [`allow_reuse_address` to 1](https://github.com/python/cpython/blob/7c4065d305228aa406675224d631f81964d12855/Lib/http/server.py#L134). 

Setting this to False `wsgiref.simple_server.WSGIServer.allow_reuse_address = False` seems to produce the desired behavior (fail fast with `OSError: [Errno 48] Address already in use`). 

PR coming soon.
