### ISSUE TITLE
run_console() broken

### ISSUE THREAD

**Issue by alvesfelipe** [googleapis/google-auth-library-python-oauthlib#96]
#### Environment details

  - Docker Image: tensorflow/tensorflow:2.3.0-gpu
  - Python version: 3.6.9
  - pip version: 20.1.1
  - `google-auth-oauthlib` version: 0.4.2

#### Code example

```python
google_auth_oauthlib.get_user_credentials(scopes, config['installed']['client_id'], config['installed']['client_secret'])
```

#### Stack trace
```
Enter the authorization code: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/src/main.py", line 71, in <module>
    main(sys.argv[1:])
  File "/code/src/main.py", line 50, in main
    handle_drive = IODriveData()
  File "/code/src/data/io_drive_data.py", line 39, in __init__
    self.service = _auth_drive()
  File "/code/src/data/io_drive_data.py", line 27, in _auth_drive
    creds = google_auth_oauthlib.get_user_credentials(scopes, config['installed']['client_id'], config['installed']['client_secret'])
  File "/usr/local/lib/python3.6/dist-packages/google_auth_oauthlib/interactive.py", line 105, in get_user_credentials
    return app_flow.run_console()
  File "/usr/local/lib/python3.6/dist-packages/google_auth_oauthlib/flow.py", line 412, in run_console
    code = input(authorization_code_message)
EOFError: EOF when reading a line```

**Comment by engelke** [comment]
Cannot reproduce the problem. The command works as intended with Python 3.6.8 and google-auth-oauthlib version: 0.4.2.
